# ===================================
#  Form Behavior Config
# ===================================

# Record name
name: Customer

# Model Form Field configuration
form: $/bedard/shop/models/customer/fields.yaml

# Model Class name
modelClass: Bedard\Shop\Models\Customer

# Default redirect location
defaultRedirect: bedard/shop/customers